### ISSUE TITLE
AppStore

### ISSUE THREAD

**Issue by Xiphe** [aaronpk/GPS-Logger-iOS#13]
Hey,

Has this been released in the AppStore? Would really love to use it or something similar.

**Comment by aaronpk** [comment]
I haven't yet, but I'm getting enough people asking that I might try that soon! For the time being you'll need to compile it yourself. Apple has a free developer account now, but the provisioning profiles only last 7 days so you have to reinstall it weekly which is a little annoying.

**Comment by Xiphe** [comment]
yeah, the reinstalling-thing is why I asked if you or s.o. else have uploaded this to the AppStore :)

thanks for the answer.

**Comment by keepcarlson** [comment]
Adding in a vote to have it released on the app store!  Thanks!

**Comment by sebsel** [comment]
+1 :)

**Comment by aaronpk** [comment]
Okay, I've had enough people asking me to submit this that I'm going to do it. Tracking progress in this milestone: https://github.com/aaronpk/GPS-Logger-iOS/milestone/1

**Comment by aaronpk** [comment]
In case you missed it, the app is now live in the app store! Download link available here: https://overland.p3k.io/
