### ISSUE TITLE
Background location / iOS11

### ISSUE THREAD

**Issue by lostfocus** [aaronpk/GPS-Logger-iOS#14]
Just a heads up - I just compiled this on the latest Xcode for an iOS11 phone and the app doesn't ask for the location permission anymore. I'll do some research on what changed and report back.

**Comment by lostfocus** [comment]
That's the culprit: https://stackoverflow.com/questions/44424092/location-services-not-working-in-ios-11

> This app has attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain both NSLocationAlwaysAndWhenInUseUsageDescription and NSLocationWhenInUseUsageDescription keys with string values explaining to the user how the app uses this data

**Comment by aaronpk** [comment]
Argh why do they keep changing the key names! Thanks for tracking this down

**Comment by sebsel** [comment]
I noticed that the blue "GPS Logger is using your location" bar is now present in iOS 11. In my settings, I see that GPS Logger has permissions to use my location when the app is on. Hope that it's related and that this fixes it :)
