### ISSUE TITLE
New way of handling notifications breaks selfsigned install of app

### ISSUE THREAD

**Issue by sebsel** [aaronpk/GPS-Logger-iOS#20]
With https://github.com/aaronpk/GPS-Logger-iOS/issues/19 you switched to a new way of notifications, but that one is only available if you are a Developer Program member. (See [this](https://developer.apple.com/support/app-capabilities/) overview from Apple.)

The errors you will get look like:
```
Code Signing Error: Cannot create a iOS App Development provisioning profile for "nl.seblog.gps". Your development team, "Sebastiaan Andeweg", does not support the Push Notifications capability.
Code Signing Error: Provisioning profile "iOS Team Provisioning Profile: nl.seblog.gps" doesn't support the Push Notifications capability.
Code Signing Error: Provisioning profile "iOS Team Provisioning Profile: nl.seblog.gps" doesn't include the aps-environment entitlement.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.0'
```

To solve this partially, I followed [this guide](https://stackoverflow.com/questions/44568009/how-to-disable-push-notification-capability-in-xcode-project).

1. go to the file `GPSLogger.entitlements` and remove the `APS Environment`-key from the list.
2. go to the main GPSLogger file, the tab 'capabilities' and switch off the notifications
   ![schermafbeelding 2017-10-02 om 12 22 24](https://user-images.githubusercontent.com/16517999/31073639-159d5b9e-a76d-11e7-8353-4f73e4fa4647.jpg)
3. maybe I hit the 'retry' button near 'Signing' on the tab 'General' a few times

This will ofcourse kill the notifications, but the rest of the app seems to work :)

Yet another reason to look out for https://github.com/aaronpk/GPS-Logger-iOS/issues/13 🙃

**Comment by aaronpk** [comment]
I wasn't actually sure if I needed to add that new entitlement to get the new API to work. It's worth trying a build without the entitlement and seeing if the notifications work. I'll push up a little change to a branch for you to try.

**Comment by sebsel** [comment]
I have it still set up as described above, and I still get some notifications. (Only the 'Location updates paused', it seems... I used to get a lot more.)

I am okay with less notifications, so I'm not doing a thing for now :)

**Comment by aaronpk** [comment]
Okay, I've reverted the entitlements change in 501187219cce9082db3c56a8b47f7745dd777264
