### ISSUE TITLE
iPad?

### ISSUE THREAD

**Issue by keepcarlson** [aaronpk/GPS-Logger-iOS#7]
Hi - any chance this will work on an iPAD?  I've been trying to install via xcode and it keeps failing so I am wondering if iPad vs. iPhone is the problem.

**Comment by aaronpk** [comment]
I think I've installed it on an iPad in the past, although definitely not in the last year or so. It's quite possible I'm missing some iPad views.

**Comment by aaronpk** [comment]
Just wanted to check back in and say I've successfully run it on an iPad running iOS 11 now.

**Comment by keepcarlson** [comment]
Thank you!  I am looking forward to trying it from the App Store!
