### ISSUE TITLE
Show speed in km/h

### ISSUE THREAD

**Issue by sebsel** [aaronpk/GPS-Logger-iOS#9]
I don't have the confidence in Objective C to add an option for this, so here's a little guide to change the mph to kmph in the code. I added a decimal point to it too.

1. Open GPSLogger.xcworkspace in Xcode and navigate to GPSLogger/FirstViewController.m
2. Change on line 124 `int` to `float` (2 times), remove `round()` and change `2.23694` to `3.6`.
    - from `int speed = (int)(round(location.speed*2.23694));` 
    - to `float speed = (float)(location.speed*3.6);`
3. Change on line 126 `@"%d"` to  `@"%0.1f"`.
    - from `self.locationSpeedLabel.text = [NSString stringWithFormat:@"%d", speed];`
    - to `self.locationSpeedLabel.text = [NSString stringWithFormat:@"%0.1f", speed];`
4. Change the labels containing `mph` to `km/h` on lines 134 to 144.
    - from `self.motionTypeLabel.text = @"mph, walking";`
    - to `self.motionTypeLabel.text = @"km/h, walking";`
5. Change on line 222 `MetersToMiles` to `0.001`
    - from `self.tripDistanceLabel.text = [NSString stringWithFormat:@"%0.2f", [GLManager sharedManager].currentTripDistance * MetersToMiles];`
    - to `self.tripDistanceLabel.text = [NSString stringWithFormat:@"%0.2f", [GLManager sharedManager].currentTripDistance * 0.001];`
6. Navigate to GPSLogger/Main.storyboard, and in the graphic interface, look for the main view, and click a few times on 'miles' in the trip area, to change it to 'km/h'. (This changes that file on various places, according to Git, but I guess that's ok.)
7. Rebuild app.

**note** This is only changing the display of the speed in the app, not what the app stores.

**Comment by aaronpk** [comment]
There is a way to use the system setting to determine the units shown, `NSLocaleUsesMetricSystem`. The app should read that value and show the appropriate units.
